### ISSUE TITLE
Track initial URL request to redirect to after login/signup

### ISSUE THREAD

**Issue by ChuckIrvine** [cleverbeagle/pup#109]
I want to implement the following functionality:

1. A potential, not-signed-up user clicks on a link to authenticated content in my web app. 
2. The user is automatically taken to my sign up page.
3. The user signs up and is then taken to the linked page.
4. I use React Router.

Is this supported by pup? Any suggestions on a way to implement?

Thanks,
Chuck

**Comment by cleverbeagle** [comment]
Hi @ChuckIrvine, this isn't directly in Pup but is possible. It involves a few steps:

1. The best place to start is by converting the `/imports/ui/layouts/App/App.js` component to [a class-based component](themeteorchef.com/tutorials/understanding-react-component-types) so that it has access to React state.
2. Next, you'll need to get access to the initial page the user is trying to access. This can come from JavaScript by looking at `window.location` when the page loads, or, you may be able to get this by implementing a [custom router history](https://reacttraining.com/react-router/web/api/Router/history-object) and [listening to it for changes](https://github.com/ReactTraining/history#usage). The idea here is that you use the `history` package to create a custom history and then pass it to the `<Router />` component as the `history` prop.
3. Once you have the location they were trying to visit, you can set that on the `<App />` component's `this.state` value. If you pass that (`this.state.redirectTo`, for example) down to your `/login` or `/signup` page, immediately after login you can say `history.push(this.props.redirectTo)` and go from there.

All of that said, I'm going to convert this into a feature request to implement into Pup. Far too many steps to have to guess/cobble together.
