### ISSUE TITLE
Add a way to programmatically strip all documents examples

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#148]
Idea from a current customer. Have a way to delete all of the example documents-related code with a single command for folks who have learned the patterns.

**Comment by merlinpatt** [comment]
We'll need to write an npm script for this. Removing files and folders is easy. The tricky part will be removing the relevant lines from files. We should assume the original lines haven't changed. Otherwise we'll have to make so many checks, it will be nigh impossible.

```
# Simple removal of files and folders

rm -r api/Documents
rm -r ui/pages/Documents
rm -r ui/pages/EditDocument
rm -r ui/pages/ViewDcoument

# Put in-file removal code here
```

Here is a list of all the files that use or mention Documents that we would need to remove lines from

```
./ui/components/AuthenticatedNavigation/index.js
./ui/layouts/App/index.js

./private/email-templates/welcome.html
./private/email-templates/welcome.txt

./api/Users/server/deleteAccount.js
./api/Users/server/exportData.js

./startup/both/api.js

./startup/server/api.js
./startup/server/fixtures.js
./startup/server/sitemap.js
```

**Comment by cleverbeagle** [comment]
Would it be possible for the specific lines to just keep a search strings file that we update whenever the documents examples change (should be rare enough to not be a chore).

**Comment by cleverbeagle** [comment]
Closing in favor of #185
