### ISSUE TITLE
Sometimes when hard refreshing the page, already logged in user doesn't login

### ISSUE THREAD

**Issue by pagesrichie** [cleverbeagle/pup#171]
Sometimes when hard refreshing the page (like manually clicking the refresh button up top in the browser), if the user is already logged in, the user doesn't login and is sent to the sign up page.  I can then hard refresh again and the user logs in.   I can sometimes refresh 10 times till i see the bug, sometimes only after one or two refreshes.

What would be the fix for this?

**Comment by cleverbeagle** [comment]
Hey @pagesrichie, for this one, have you modified any parts of the login process? If anything, I'd expect the user to be redirected to `/login` instead of `/signup`. 

It's very likely that if it only happens once in awhile, it's because the client-side Redux store hasn't updated quickly enough with the current user and the redirect kicks in to boot the user.
