### ISSUE TITLE
Two meteor apps using one database

### ISSUE THREAD

**Issue by pisacode** [cleverbeagle/pup#195]
Hi, I am using pup for two meteor applications sharing one database, one is for the client and one is for the server.

After creating some collections on the server app, I am trying to feed client from that collections. However, I couldn't figure out how to import the server collection to client. Since the client app also has access to the same database,  I have tried `const DocumentCollection = Meteor.Collection('Documents')` but it throws this error `Error: this._maybeSetUpReplication is not a function [500]` 

When I do `const DocumentsCollection = new Mongo.Collection('Documents');`

I can reach the documents just fine, however I am a bit confused because of this because that line supposes to set up a collection. So could there be some replication?

So my question is, what is the right way to reach server app collections and from the client app?

Thanks

**Comment by choncj** [comment]
Hey @pisacode to me it seems like your problem is out of scope for this boilerplate. Still i would like to direct you in the right direction.

[- Connecting separate Meteor Web-Apps and Mobile Apps](https://medium.com/@aidobreen/setting-up-a-meteor-project-with-remote-mongodb-using-mup-and-digitaloean-7c9592622189)
[- Insert data to external mongodb with meteor app](https://stackoverflow.com/questions/43801698/insert-data-to-external-mongodb-with-meteor-app)

Hope this helps you figuring it out.

**Comment by merlinpatt** [comment]
@pisacode why are you separating the client and server app?

**Comment by pisacode** [comment]
Hi @merlinpatt ,

Main reason is the app is a cordova exported mobile application and admin features are way to big to included with the mobile app. Therefore having two application for admin and normal users seems more convenient

**Comment by merlinpatt** [comment]
You should be able to do this by setting MONGO_URL when you run the second application

To do this locally,

1. Run one app first (shouldn't matter which one).
  * This will run the app on port 3000 and the database on 3001
2. Run the second app with `MONGO_URL=mongodb://127.0.0.1:3001/meteor meteor --port 3002`
  * This will run the second app on port 3002 and the database on 3001

To do this in production, you just need to make sure that the MONGO_URL environment variables are pointed at the same Mongo URL.
