### ISSUE TITLE
Mocks library

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#2]
There's a lot of internal code for Meteor that will need mocking. There are quite a few third-party solutions to this already, but they're a bit piecemeal. It'd be best to sample from these existing implementations and combine them into something that we can manage and expand under Pup.

Need mocking for:
- Meteor internals (e.g., Meteor.users, Accounts, etc) <-- the "big one"
- Mocking MongoDB collections
- NPM packages used in Pup
- Example third-party request (Github?) library

**Comment by ninjaPixel** [comment]
Rather than going to all the effort of mocking Accounts, MongoDB etc how about using an end-to-end framework, for these tests?
I've had great success with [Test Cafe](https://github.com/DevExpress/testcafe) to test things like a/c creation, logging in etc.
The benefits of doing it this way are:

1. We also test the UI
1. We don't have to write mocks or keep them up-to-date

**Comment by cleverbeagle** [comment]
Do you have any examples of this being put to use in Meteor? On the surface this sounds ideal from the acceptance test side of things. How does it handle things like unit testing (or are you suggesting we use this independently of unit/integration tests)?

**Comment by ninjaPixel** [comment]
I use Test Cafe for Gluless (which is a Meteor project). I can show it to you on a Hangout if you like.

It's completely separate to my unit tests. I generally unit test whatever can be unit tested, but more involved stuff (e.g. something that require a user account, or testing of the UI) is done with Test Cafe.
