### ISSUE TITLE
Uncaught TypeError: $(...).validate is not a function.

### ISSUE THREAD

**Issue by Salamit** [cleverbeagle/pup#226]
I'm getting the following issue, `Uncaught TypeError: $(...).validate is not a function.` I recently updated from jquery ^2.24 to jquery ^3.1.1 because of the Cross-Site Scripting (XSS) issue raised by npm audit.

**Comment by cleverbeagle** [comment]
This is a known issue. jQuery Validation is dependent on the < 3 version of jQuery so it's a catch-22. We'll need to move away from jQuery Validation at some point but it's low priority for now.

**Comment by manacim** [comment]
Any update on this? I am running jQuery 2.2.4 and I'm still getting the error on those 2 pages.

**Comment by cleverbeagle** [comment]
@manacim see comment above, this is currently a nofix because we're dependent on an earlier version of jQuery. I would double check that you have `2.2.4` installed by doing a full `meteor npm install`. If that doesn't work, try deleting the `node_modules` directory at your root and then run `meteor npm install` again.

**Comment by manacim** [comment]
@cleverbeagle yeah thanks I got it working. I'm completely new to meteor and this framework.
