### ISSUE TITLE
Research TypeScript

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#266]
THIS DOES NOT MEAN PUP IS MOVING TO TYPESCRIPT.

I've seen/heard a lot of great things about it and want to give it a fair try before shrugging it off as another CoffeeScript type of thing.

Some things to evaluate:

- Does it help to make Pup more stable by improve code quality?
- Does it help developers to improve their craft or just learn another dialect?
- How selective can usage be? Can we include but not force devs to depend on it?
- What are Microsoft's long-term plans for the language?
- What does the licensing look like? Any weird legal gotchas?

**Comment by jesperordrup** [comment]
If the javascript developers wanted typescript then javascript would have adapted the ways of typescript long ago. 

> Just don't do it! the project is getting momentum and lots of people know JS and will collab on this but if you turn into TS it will make it hard to adopt or extend.

Agree

**Comment by cleverbeagle** [comment]
Oof! Noted, thanks for the thoughts folks.

**Comment by nicu-chiciuc** [comment]
I think that TS should be mandatory for any big SPA. Currently I'm working on a project which doesn't use it and I feel that I'm spending too much time just trying to figure out what goes where. TS is not the best solution but it definitely forces a better code base. I'm not sure what "the javascript developers" wanted, but they'd probably still use jQuery if there weren't some disruptive changes in the ecosystem.

Also, surprisingly, from my experience React works much better with TS than Angular does.
@meteorplus as strange as it may sound but dynamically typed languages are just a subset of statically typed languages (https://existentialtype.wordpress.com/2011/03/19/dynamic-languages-are-static-languages/).

At the same time it's important not to force the usage of TS (like Angular did). I guess having js files with corresponding type definitions would be a good compromise.

**Comment by ceigey** [comment]
Hi all, not a regular but evaluating Pup for a project, and TypeScript was something we wanted to adopt. So here's my thoughts.

---

The approach in the community seems to be "set things up so TypeScript can be used if needed". In any case, this is the philosophy TypeScript embraces by being a relatively strict superset of JavaScript, which we see in how the dev team approach TC39 proposals*.

It may be better, provided the time and energy is there, to simply structure things so you can use TypeScript out of the box if you want, and provide some .d.ts files as needed, otherwise allowing developers to use JavaScript. I personally would appreciate that.

I know from experience that it is difficult to set up TypeScript > 2.8 on Meteor, as an official TypeScript solution is still being developed apparently, and community solutions can get a bit hacky (or, in the case of using plain old `tsc`, messy when orphaned .js files are lying around in a mixed TS/JS project) and thus are perhaps not suitable for those getting started.

In addition to TS & Flow, there is also runtime type checking solutions, e.g. https://github.com/sanctuary-js/sanctuary, which could be added in by any developer as an npm dependency and give them a bit more oversight. On that note, functional programming libraries (e.g. Fantasy Land) don't work 100% with TypeScript due to type system limitations, and the type definitions for those often have to make compromises.

*_There's a lot of community desire for them to implement pipeline operators and pattern matching and so on, but it simply won't happen. Even TypeScript's early adoption of decorators has a bit of regret associated with it, because the proposal spec has changed a bit even at this late stage, I believe._

---

> Does it help to make Pup more stable by improve code quality?

Given that Pup is largely React & Apollo oriented and has proptypes, I'd say you guys get a lot of runtime type checking as is. You could write TypeScript `interface`s and use them for a bit of writing-time type safety e.g. intellisense in VS Code.

> Does it help developers to improve their craft or just learn another dialect?

It does make JavaScript's duck-typing / structural type system a little more explicit. I'd say the overhead is different to that of learning CoffeeScript - it's almost 1:1 JavaScript, but you have to learn how they annotate types (and generics, depending on how lucky you are).

> How selective can usage be? Can we include but not force devs to depend on it?

Generally opt-in, but TypeScript tends to (naturally) get confused when you start using functions imported from plain JS objects (because it's very hard to duck type a function argument). At that point, it will begin complaining about missing types. You can either write those types in your .ts file or in a .d.ts file, or just force it to transpile anyway in some cases.

But this is only an issue if Pup is written in JS and the user is writing in TypeScript.

> What are Microsoft's long-term plans for the language?
Roadmap (doesn't necessarily answer this question)
https://github.com/Microsoft/TypeScript/wiki/Roadmap

Presumably they're waiting for denoland/deno to take off so they can try taking over the JS world :laughing:

I think this question might need to be more specific.

> What does the licensing look like? Any weird legal gotchas?
Appear to be Apache 2.0.
https://github.com/Microsoft/TypeScript/blob/master/LICENSE.txt

**Comment by cleverbeagle** [comment]
Thanks for sharing and all of the detail @ceigey. I'll keep all of this in mind.

Re: your question about the question re: licensing, this is regarding whether or not TypeScript's own licensing will work well with our MIT license and desire to keep things as free as possible (i.e., is there some weird patent clause like React used to have).

**Comment by ceigey** [comment]
Ah, apologies @cleverbeagle, my brain was on "trying to be helpful"-autopilot there ;-)

Some updates from experimenting:
There's quite a few solutions being proposed here for Meteor + TypeScript: https://github.com/meteor/meteor-feature-requests/issues/285

I found that meteor/ecmascript + TypeScript were fighting as far as imports and dependencies were concerned with `adornis:typescript`, leading to things like `import` statements finding their way into the code the browser received, and I can only assume that you would have to start a new Meteor project from scratch for that plugin to work as expected. 

I also came across a few solutions outside of that thread, like making Webpack handle the main builds. But they didn't address all my concerns.

In the end, the solution I'm using for converting Pup into a TypeScript application is as follows:

1. Temporarily comment out  `.githooks/pre-commit.sh` because the project restructuring throws it into some sort of indefinite loop (?) until it times out (I'm yet to fix that at this stage, still early days)
2. Restructure the project so all JavaScript source is in `src`, and add a `build` folder.
3. Add a `tsconfig.json` file (see below for example)
4. In `package.json`, change the Meteor startup paths to use the `build/` folder
5. Change GraphQL `.gql` files into `.ts` files, using `graphql-tag` (include fragments using this documentation for Angular as a guide: https://www.apollographql.com/docs/angular/features/fragments.html). You'll need to use ES2015 export syntax correctly and double check that your imports are updated (both the paths and imported symbols!) - I recommend using VS Code's search & replace functionality, with "Files to include" being `src/**/*.js`, and then searching for things like `from '../../mutations/`. *If GraphQL complains about being passed an Object and not a string, it means your imports are broken, likely*.
6. Run `tsc` and populate your `build` folder with `.js` files

At this stage, because the project as a whole has not been converted to TypeScript, not much has actually been achieved. But assuming I haven't missed any critical steps, you should get the Pup welcome screen when you run `meteor npm run dev`.

You might also want to do some house cleaning after completing all those steps, otherwise you'll end up with massive commits of hundreds of files at once.

In my case, **I also did the following**:
* I added `build/**/*.js` and `build/**/*.jsx` to `.gitignore`.
* I took `ui/pages/Documents/index.js` and made an `index.tsx` file instead, and used it as a beach-head for identifying missing types (there's a lot of them, `npm i -D @types/...` will become your friend, but you will need to get your hands dirty for things like `const Documents = ({ data, mutate }) => (`, where `data` and `mutate` are implicit `any`'s, which subverts the point of TypeScript and gives me a red squiggly line)

**Some other issues that I need to address**:
* testing `// @ts-check` on some remaining JS files.
* Converting every JS file to TypeScript 
* Making sure tests aren't broken (I'm almost certain they are, due to the addition of the `src` and `build` folders)
* Adding a Babel plugin to pre-process the `gql` template strings.
* Reactivating `.githooks/pre-commit.sh`
* Figure out a nice documented process that helps keep builds up to date.

On the subject of builds:
1. Run `./node_modules/.bin/tsc` once your `tsconfig.json` file is set up
2. Run in one terminal `meteor npm run dev`
3. Run in another terminal once the server is fired up `./node_modules/.bin/tsc --watch`

Note that as Meteor begins updating, `tsc --watch` will begin repainting its output constantly until Meteor has finished. Not sure why.

**Alternative approaches**:
* Use flowtype. Works nicely with Babel, I imagine you could easily add that to Meteor. But Flow has its own issues - smaller community, so less community defined typings, and this can get nasty when you have an entire node_modules worth of untyped JavaScript. TypeScript tends to ignore those. Depends on whether you enjoy documenting foreign library interfaces!

* Use more runtime typing packages, if needed. Meteor + Babel + GraphQL + React prop-types means you already have a lot of development runtime type checking. I can imagine using `sanctuary`, `sanctuary-def` and `hm-def` (or `hm-def-light`) could lead to something nice if you're a fan of Hindley-Milner type systems like Haskell's.

---

I think the biggest barrier is there being no official TypeScript plugin for Meteor yet, despite rumours in 1.8. Once such a plugin comes out, I'm hoping that a lot of compromises you'd have to make above are eliminated, e.g. changing the `.gql` files to `.ts` ones (I really like the GraphQL icon that comes with the Material Icon Theme in VS Code :laughing: ).

---

Sample `tsconfig.json` file, keep in mind some bits are lazy shotgun-style solutions to problems I was facing, e.g. all the libs I've included just to keep TypeScript happy.
```json
{
    "compilerOptions": {
      "outDir": "./build",
      "module": "es2015",
      "target": "es2018",
      "jsx": "preserve",
      "lib": [ "es2015", "es2016", "es2017", "es2018", "esnext", "dom" ],
      "moduleResolution": "node",
      "allowJs": true,
      "strict": true,
      "esModuleInterop": true,
      "keyofStringsOnly": true,
      "allowSyntheticDefaultImports": true,
      "baseUrl": "."
    },
    "include": [
        "./src/**/*.ts",
        "./src/**/*.tsx",
        "./src/**/*.js",
        "./src/**/*.jsx"
    ]
  }
```
