### ISSUE TITLE
Email.send headers, not showing up in mailgun

### ISSUE THREAD

**Issue by Falkovic1993** [cleverbeagle/pup#296]
Hey Ryan, 

First of, thanks for the awesome work you have done with Pup! 

Not sure if this is related to Pup, or if there is something obvious I'm missing, but I'm having some problems sending custom headers into Mailgun, such as the `X-Mailgun-Variables` so I can access users variables from the webhooks there. 

Here is my sendEmail code: 
`return sendEmail({
    to: mail,
    from: from <test@mail.dk>,
    subject: ${subject} (${people} pers. - ${date} - ${time}),
    'X-Mailgun-Variables': { test: 'test1232131' },
    headers: { 'X-Mailgun-Variables': { test12: 'dasda' } },
    languageCode,
    template,
    messageId,
    templateVars,
})`

Email is sent correctly but the headers don't show up in Mailgun, have you tried something similar or have an example on how this is done with the sendEmail function?

Thanks!

**Comment by cleverbeagle** [comment]
Hey @Falkovic1993. I haven't tried this before, but the `sendEmail()` method doesn't do any filtering of this property. It's a wrapper around Meteor's `Email.send()` method which supposedly supports the `headers` field. 

The options you pass to `sendEmail()` (the Pup function) are relayed directly to that call so they shouldn't be dropped in any way (see [here](https://github.com/cleverbeagle/pup/blob/master/modules/server/sendEmail.js#L25)).

To debug this, I'd temporarily remove your `MAIL_URL` from your settings files and then try to send the same email again. This should log the full contents of the email to the server console (terminal). If you look in there and see the headers being passed, then the issue is going to be on the Mailgun side.

If they're not included, let me know and I can play around a bit.

**Comment by Falkovic1993** [comment]
Hey, @cleverbeagle thanks for getting back so quick! 

I ended up using the mailgun API, my testing and understanding it should also be faster to just use the API instead of the SMTP. :) 

So I never got to try out your suggestion.

**Comment by cleverbeagle** [comment]
Sounds good, @Falkovic1993.
