### ISSUE TITLE
react-bootstrap Form not rendering properly.

### ISSUE THREAD

**Issue by ChuckIrvine** [cleverbeagle/pup#33]
If I import the necessary react-bootstrap components and replace the App.js/App function with:
```
const App = props => (
  <Form inline>
    <FormGroup controlId="formInlineName">
      <ControlLabel>Name</ControlLabel>
      {' '}
      <FormControl type="text" placeholder="Jane Doe" />
    </FormGroup>
    {' '}
    <FormGroup controlId="formInlineEmail">
      <ControlLabel>Email</ControlLabel>
      {' '}
      <FormControl type="email" placeholder="jane.doe@example.com" />
    </FormGroup>
    {' '}
    <Button type="submit">
      Send invitation
    </Button>
  </Form>
);
```
The form doesn't render per the react-bootstrap component docs. See (https://react-bootstrap.github.io/components.html#forms-inline). Specifically, the ControlLabel components do  not render inline.

**Comment by cleverbeagle** [comment]
Hi @ChuckIrvine this is due to this style [here](https://github.com/cleverbeagle/pup/blob/master/imports/ui/stylesheets/forms.scss#L7). You'll want to change that to just be `display: inline;` so it doesn't break the inline behavior above. If you're looking to mix and match, you can update the styles here to be:

```

form:not(.inline) {
  label,
  .control-label {
    display: block;
  }
  
  label.error {
    display: block;
    margin-top: 8px;
    font-size: 13px;
    font-weight: normal;
    color: $danger;
  }
}
```

This is untested but should work. If it does what you're looking for, can you reply here? Seems like worthwhile patch.

**Comment by ChuckIrvine** [comment]
If I just change the one line to “display: inline;” - that works. However, if I use your style code below, the problem remains. Going with the one liner for now. Thanks a lot. Your code has helped me immensely.

**Comment by cleverbeagle** [comment]
Okay, good to know. I'll have to see how we can exclude these styles entirely from inline forms so that tweak isn't necessary.
