### ISSUE TITLE
How to upgrade from v1-> v2

### ISSUE THREAD

**Issue by consciousweb** [cleverbeagle/pup#340]
I performed the upgrade as https://cleverbeagle.com/pup/v1/upgrading-pup instructs (resolved all conflicts etc) and im unable to access my meteor methods. What needs to be done get my v1 build upgraded to v2? I understand v2 relies on gql and other technologies, but can i not pull in my bulk meteor methods file and convert it over time?

**Comment by cleverbeagle** [comment]
Howdy @conciousweb, you can pull your methods over, it will just take the time to do it. The underlying technology to support methods still exists in Pup, though.

Re: upgrading v1 and not being able to access methods, what errors do you get (or does stuff just not work)?

In general, because Pup isn't like a traditional package or library, an upgrade to a new major version means copy-pasting files incrementally, or, starting a new repo from v2 and copying over your custom functionality (that doesn't modify what's in the boilerplate).

**Comment by conciousweb** [comment]
I use a bulk methods file in a root server folder and all methods are simply not found.

**Comment by cleverbeagle** [comment]
Is that file imported into `/startup/server/api.js`? If not, add it there and they should start working as expected.
