### ISSUE TITLE
is this repo still maintained?

### ISSUE THREAD

**Issue by WanielDeiss** [cleverbeagle/pup#346]
do you have the time to maintain this project?

**Comment by cleverbeagle** [comment]
At the moment this project is on hold and I'm evaluating a move away from Meteor.

**Comment by WanielDeiss** [comment]
thanks for your answer!
why do you want to move? and what do you have in m ind for a move?

**Comment by cleverbeagle** [comment]
I'd like to just do a vanilla Node.js application so there are no ties to a specific framework.

The goal is to limit the "X is dead" drama or the constant need to jump to a new framework. I want Pup (and whatever its successor is) to be stable and focused on helping people just build stuff without having to constantly evaluate new tools that may or may not improve the ability to build products.

I've gotten caught in this trap enough times to understand that the long-term flexibility of not using a framework is better than the short-term convenience of using one.

**Comment by inkiltie** [comment]
> At the moment this project is on hold and I'm evaluating a move away from Meteor.

So sad to hear that MeteorChef, CleverBeagle will move away from Meteor. 

But this comment gave me some bit hope that Pup will thrive: https://forums.meteor.com/t/why-not-meteor-in-2020/52847/33

And by the way, are there any updates on Fur? https://cleverbeagle.com/fur

**Comment by cleverbeagle** [comment]
@inkiltie it is sad, but for the sake of my own sanity I think it's for the best 😂 I spent several years chasing Meteor's leadership around to no end and I'd rather move on. That said, Meteor as a _tool_ is still excellent and I'm still working with it daily.

Pup the repo isn't going anywhere, but I don't have any plans to do any major work on it (maybe some dependency bumps here and there or merge some of the long-standing PRs).

I decided to stop work on Fur and focus on other things.

The "why" behind these two changes is that I was doing too much stuff. It was a capability vs. capacity problem and late last year I got burned out. I decided to focus my efforts on a SaaS product for a while (https://oncommand.io, built with Pup!) and think more carefully about where to take my JS work and teaching efforts.

I *do* have an answer to that now, but since it's just me working on this stuff I can't say when that will be. I've acknowledged a lot of the issues in the JS community and ecosystem and am thinking of some ways to solve those problems. I'll be back :)

P.S. Thank you for your continued interest and attention, I really appreciate it.

**Comment by inkiltie** [comment]
@cleverbeagle no matter what is going to happen next, thank you for the Pup. Personally, I think this is the best tool to build web apps of any difficulty even today. This is not only a boilerplate but literally a small and sturdy GUI-based CMS with full control over everything, e.g. just apply your styles and have a blog with markdown editor and comments. And I'm not even talking about accounts management out of the box. Sometimes it reminds me the simplicity of WordPress :)

> I decided to stop work on Fur and focus on other things.
> 
> The "why" behind these two changes is that I was doing too much stuff. It was a capability vs. capacity problem and late last year I got burned out. I decided to focus my efforts on a SaaS product for a while (https://oncommand.io, built with Pup!) and think more carefully about where to take my JS work and teaching efforts.

I've been in such a situation myself, so I fully understand. Once again I appreciate your work and good luck in your current and future endeavors.

**Comment by arthurkirsz** [comment]
Hey Ryan, Just wanted to add my contribution to this thread.
I have been designing, developing and maintaining a software based on Meteor and inspired from _base_ (wasnt even pup at that time !) for the past 3-4 years.

Your work at themeteorchef has been invaluable to me. 
It taught me a lot about meteor, and I always enjoyed your "code style", the way you think and design stuffs. Anyway, wish you the best for what's next, keep us informed !

**Comment by anthonyferreol** [comment]
@cleverbeagle Same here, thanks for everything!  I have been using base, then pup, to create and maintain a web-based interface for a medium business (to handle all business-related things with the employees). You taught me many things and definitly shaped my career path! Wish you the best 🥰

**Comment by evolross** [comment]
@cleverbeagle Same here. themeteorchef.com has been **invaluable** especially about four or five years ago when I first got started.  My Stripe code is still based on your articles.  Thanks so much everything. Hopefully you keep up with community work in some way. Fan of your blog and podcast too.
