### ISSUE TITLE
Error when launching a new app  bcrrypy@1.0.3

### ISSUE THREAD

**Issue by GilbertMizrahi** [cleverbeagle/pup#51]
It says failed at the bcrrypy@1.0.3 install script 'node-pre-gyp install --fallback-to-build'

**Comment by pilarArr** [comment]
Did you use `meteor npm install` or `npm install`?

**Comment by GilbertMizrahi** [comment]
npm install as per the instructions

**Comment by pilarArr** [comment]
Yes, the instructions use `npm install` instead of `meteor npm install`, I always use `meteor npm install` though, this is what [meteor has to say about it](https://docs.meteor.com/commandline.html#meteornpm), I'm not sure if it says `bcrypt` would give you problems or not, but it looks like it could be issue. You could try reseting your packages and doing the installation with `meteor npm install` instead to see if it solves the issue.

**Comment by GilbertMizrahi** [comment]
`meteor npm install` solved the problem. Thanks.

**Comment by cleverbeagle** [comment]
@pilarArr @GilbertMizrahi just updated the docs to prefer `meteor npm install` over `npm install` moving forward: https://cleverbeagle.com/pup/v1/getting-started. Going to close this for now but feel free to open if you have any more issues.
