### ISSUE TITLE
What testing framework(s) should we use?

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#67]
@pilarArr @ninjapixel

I wanted to start an official thread on this so we can make a decision in respect to what tools we'd like to use. @pilarArr and I have discussed Jest/Enzyme (and I believe she's starting to think about/work on this) and @ninjapixel has suggested Test Cafe for acceptance tests.

Can we outline the following in this issue?

1. Test frameworks that you've used with Meteor that work well for unit testing.
2. Test frameworks that you've used with Meteor that work well for acceptance testing.
3. Arguments in favor of those tools.

Ideally we can make a decision over the next week and then start making headway on testing. I'd also like us to figure out a good implementation for handling continuous integration as well as code coverage (any advice you have on either is welcome).

**Comment by pilarArr** [comment]
I think we should agree on how to organise the test files. I've seen 2 versions of it:
- Having a single test folder for all of them
- Storing them with the component/module/script and naming it with `.test.js`
- Something in between

Right now Jest scans the whole project and detects these `.test.js` files automatically. But I don't know how the other tools approach this.

**Comment by cleverbeagle** [comment]
I can see arguments for/against the single folder, but in respect to making it easy to follow, I'd imagine having tests alongside the code would be best. For example, testing something in modules:

```
/imports
--- /modules
------ parse-markdown.js
------ parse-markdown.test.js
```

A bit clunky because it adds some weight, but really easy to understand. @ninjaPixel is something like this possible with Test Cafe or do we have to have all of the tests in one spot?

**Comment by ninjaPixel** [comment]
I prefer having the unit tests alongside the code. It makes things easier to find and makes the imports simpler. Anything to reduce the friction when it comes to writing tests is a plus!



With respect to the end-to-end tests (e2e), the finest level of granularity that you can test at will be the page level, so you'd never place a `.test.js` file deeper than `/imports/ui/pages/foo`. In reality, most tests will span pages, so you'd end having most of your tests in `/imports/ui`.
I think it makes more sense to have the e2e tests in a sibling directory to the app's code - unit tests and end-to-end tests will both have the same `.test.js` extension and it will be confusing as to what type of test a file belongs to if they all appear in the same place, plus it'd make setting up the test suites over-complicated because you'd have to do some sort of globbing to make sure each suite loaded the correct test files. We _might_ be able to get around this by naming our files `foo.unit.test.js` and `foo.e2e.test.js` but that would need investigation.


I'd set it up like this:

```
/app
--- /.meteor
--- /imports
/tests
--- account-creation.test.js
--- login.test.js
--- create-new-document.test.js
```

I realise that this will slightly change the structure of `pup-pro`, but if you're thinking of launching a React Native version at some point in the future, we'd need this file structure anyway because the RN code needs to live outside of the `app` directory. Taking this approach would also make it simple to swap (or add) different e2e frameworks.

**Comment by ninjaPixel** [comment]
Oh yeah, one other thing... We'll need to install dependencies for Test Cafe (or any e2e suite) and we don't want those dependencies to be shared with the app! Hence we defo want to stick the e2e stuff in a separate directory.

**Comment by cleverbeagle** [comment]
Decided! Jest for unit testing, Enzyme for React components, and Test Cafe for E2E/Acceptance tests.
