### ISSUE TITLE
Come up with a naming convention for unit tests and files

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#76]
Need to get a convention for:

- File names under `/imports` (e.g., we need to test individual modules in `/imports/modules` as well as React components w/ Enzyme in `/imports/ui/...`)
- Naming each file/test suite.
- Naming each test 'If passed a markdown string, properly converts to HTML'.

**Comment by cleverbeagle** [comment]
Some conventions coming into focus (going to update this comment as I go):

- If a file in `/imports/modules` is tested, the file should be located directly next to that file (e.g., we can expect to find `parse-markdown.js` and `parse-markdown.test.js` in the same directory).

**Comment by cleverbeagle** [comment]
In order to run tests written with ES6+ code, we need to include a `.babelrc` in the root. To placate Meteor's Babel when using `babel-jest`, we needed to install `babel-config-meteor` and then add a `.babelrc` like this:

```
{
  "presets": ["meteor", "env"]
}
```

Where `meteor` applies to the Meteor version of Babel and `env` is used by the `babel-jest` package used in conjunction with Jest. Using one or the other causes compile errors for both, so each is required. Not a horrible trade-off all things considered. So it's clear, this makes our `devDependencies` look like this:

```
  "devDependencies": {
    "babel-jest": "^20.0.3",
    "babel-preset-env": "^1.6.0",
    "babel-preset-meteor": "^6.26.1",
    "enzyme": "^2.9.1",
    "eslint": "^4.6.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-meteor": "^4.1.4",
    "eslint-plugin-react": "^7.3.0",
    "jest": "^20.0.4"
  },
```

**Comment by cleverbeagle** [comment]
@ninjaPixel playing with your idea of splitting off method code into standalone functions to tests. Definitely the ideal scenario in respect to testability, but still getting boxed in by internal deps (e.g., meteor/mongo on collections). For example, a module like this:

```
// /imports/api/Documents/methods/insert.js

import { Meteor } from 'meteor/meteor';
import { check } from 'meteor/check';
import Documents from '../Documents';

export default function (doc, userId) {
  check(doc, {
    title: String,
    body: String,
  });

  try {
    return Documents.insert({ owner: userId, ...doc });
  } catch (exception) {
    throw new Meteor.Error('500', exception);
  }
}
```

And then the test:

```
// /imports/api/Documents/methods/insert.test.js

import { Mongo } from 'meteor/mongo';
import Documents from '../Documents';
import insert from './insert';

const testDocument = { title: 'Test doc', body: 'Test doc body.' };
const testUserId = 'test-user-id';

test('Inserts a document into the documents collection.', () => {
  const expectedDocument = { ...testDocument, owner: testUserId };
  insert(testDocument, testUserId);
  expect(Documents.findOne({ ...testDocument, owner: testUserId })).toEqual(expectedDocument);
});
```

Jest throws a tantrum about `meteor/mongo` :(

<img width="659" alt="screen shot 2017-09-30 at 3 52 31 pm" src="https://user-images.githubusercontent.com/23730234/31049375-64a15f00-a5f7-11e7-9b76-11cb34356b09.png">

The good news is that handling the mocks isn't too bad [based on what I read here](https://forums.meteor.com/t/mocking-meteor-package-imports-in-jest/27780), so I'm open to investing in it if it means less hoop jumping to write tests.

Any thoughts/see anything I'm missing?

**Comment by ninjaPixel** [comment]
It doesn't look like you're missing anything.
That's a shame that we have to write mocks... 
Perhaps we should re-evaluate if this is the right tool, after you've hooked up a simple test.

**Comment by cleverbeagle** [comment]
The only other option is to [use one of the driver packages for Meteor](https://guide.meteor.com/testing.html), but like we discussed on Friday I'd like to avoid tight coupling to Meteor-specific tools to give us more flexibility in the long-term. I'll keep playing and see how crazy it gets with mocks (in theory we can get what we need in a single JS file). 

On a semi-related note, we also need to keep documentation in mind so extending this sort of stuff is as clear as possible for others.

**Comment by cleverbeagle** [comment]
https://www.okgrow.com/posts/real-world-unit-testing-with-meteor-and-jest

**Comment by ninjaPixel** [comment]
Following on from that article, my feeling is that we have to jump through too many hoops to use Jest. I'm not keen on writing mocks because we need to actually test that documents get inserted into the database etc. (this isn't testing MongoDB, it's testing our code). We need to test that our schema validation does its job, test that any observer functions get triggered, etc. Why mock this all out when we can just call the actual code directly? I just don't get it (please explain, as I genuinely feel like I'm missing something here!); yeah, maybe the meteor/mongo package gets updated - with a bug - and our tests fail, but that's exactly what we want to happen as we wouldn't want to deploy a bogus build, regardless of whether it's our fault or that of a third-party library.

From my current knowledge of test frameworks w/ Meteor, I think the highest impact approach is to use Mocha for testing our JavaScript logic  (including the code that modifies documents in our database) as it 'just works' and is easy to set up.

We could additionally use Jest to test our React components. Though I'm not sure how easy it will be to test the components that use the react-meteor-data higher order component :scratch-head: I guess it would just mean more mocks, or splitting the components out into 2 files, so that we can explicitly pass fake meteor data to them as props.

Our end-to-end tests will test our components, so I don't feel like we need to use Jest. Even more so once we set-up tests on a CI server (where it doesn't really matter that the E2E tests take longer to run)

**Comment by cleverbeagle** [comment]
> I just don't get it (please explain, as I genuinely feel like I'm missing something here!)

I felt the same way, but ultimately the need to mock comes down to the environment the tests are executing in. In order to just run our code (which, you're right, would be ideal), we need access to the full Meteor environment. Jest doesn't have access to this. 

Focusing just on "why Jest?" long-term I want to focus on decoupling third-party tooling from Meteor directly. Meaning, as much as possible, we want to avoid people learning concepts that will only ever work in Meteor. Because testing is a massive part of software development, even if it's frustrating, it'd be good to align with the broader JS community if we can.

Another plus with Jest is that it's one of the rare testing tools that "just works" in respect to defining and executing tests. You don't have to fight with a separate test runner or install 50,000,000 packages—you write your tests, call `jest` in the terminal and you're done. From the perspective of a beginner, that makes it really tempting to use.

Looking at mocks, too, consider that we're not re-implementing the full functions. We're just saying, "hey, Jest, there's a function here that we expect our code to call. Just use this mock function that simulates the behavior." It seems like that's clear, but just to be certain.

All that said, I'm happy to explore Mocha as well. The big concern is just ease-of-use and explanation. The solution with the least hoops to jump wins in my opinion—I could care less who makes it or if it's popular :p
