### ISSUE TITLE
found a very weird bug when modifying pup, how do i diagnose what is wrong?

### ISSUE THREAD

**Issue by sw-yx** [cleverbeagle/pup#8]
so i have been trying to modify pup to merge the New Document and Edit document pages into basically one Upsert document page (since the editor is the exact same i figured it would be easy) but it is very strange: when I merge them (this potentially supplying a `doc` that is `null`) the fields have their `defaultValue` populated correctly but they arent _displaying_ in the actual browser. I have googled around this problem and apparently it could potentially be due to some sort of javascript clearing the field without my knowledge? how can I diagnose what is going on here? 

sorry for the very open ended question, hoping someone familiar with meteor is able to point me in the right direction.

**Comment by cleverbeagle** [comment]
@sw-yx I'm not entirely sure, but this may be a React gotcha. If you switch the `defaultValue` prop to just be `value`, do the fields fill as expected? If so, the inputs may need to be switched to "controlled" inputs, meaning, instead of relying on a `defaultValue` prop, you use a `value` and an `onChange` prop and set the values on state.

If the switch from `defaultValue` to `value` works, let me know here and I can offer up an example of the latter.

**Comment by sw-yx** [comment]
@cleverbeagle sorry i havent had time to test this out - will come back again if this is a more pressing issue. thanks for your response nevertheless!
